#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -compatible -g -fpp -free -C=all
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -compatible -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = -I.. 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_LibPath = -L'../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib64' -L$(fblib) -L'../../../../../../../../Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/mkl' 
NI_LDFLAGS = 
NI_Link = nagfor
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#def file
NI_DEF = KernelyzeBaseNagDLL.def

#Output file
NI_OUTPUT = KernelyzeBaseNagDLL.dll

#Target name
NI_TARGET = KernelyzeBaseNagDLL.dll

#Object files
NI_OBJS =	 \
	all_num_opt_mats_asymm.o \
	binomial_coeffs.o \
	borsuk_lower_bound.o \
	brent.o \
	chebyshev_points.o \
	compfunc_kernel.o \
	compute_a_and_b_matrices.o \
	compute_a_matrix.o \
	constants.o \
	eigen_rankn_kernel.o \
	eigen_rankn_kernel_of_params.o \
	eigen_rankn_params.o \
	factorial.o \
	falling_factorial.o \
	find_all_zeros.o \
	find_rel_optima.o \
	hermite_polynomial.o \
	integral_kernel_disc.o \
	integral_kernel_measure.o \
	integral_kernel_singlevar.o \
	integral_neigen_disc.o \
	integral_neigen_svar.o \
	integral_nmonom_disc.o \
	integral_nmonom_svar.o \
	integral_nsect_disc.o \
	integral_nsect_svar.o \
	integral_rankn_svar.o \
	itoa.o \
	kernel.o \
	kernel_bachelier.o \
	kernel_blackscholes.o \
	kernel_cauchy.o \
	kernel_expprod.o \
	kernel_gaussian.o \
	kernel_neigen.o \
	kernel_nmonom.o \
	kernel_nsect.o \
	kernel_proc_ptr.o \
	kernel_summable.o \
	linear_combo_kernel.o \
	monomial.o \
	moore_penrose_inverse.o \
	mrgrnk.o \
	normal_distn.o \
	num_opt_rankn_kernel_asymm.o \
	num_opt_rankn_kernel_of_params.o \
	num_opt_rankn_params.o \
	option_formulae.o \
	quicksort.o \
	remez_step.o \
	remez_variant.o \
	set_precision.o \
	singlevar_func.o \
	singlevar_proc_ptr.o \
	taylor_series_rankn_kernel.o \
	taylor_series_rankn_kernel_of_params.o \
	taylor_series_rankn_params.o \
	tk_simple_lapack.o \
	unirnk.o \
	worst_rho_and_gamma.o

#Depend Object files
NI_DOBJS =	 \
	all_num_opt_mats_asymm.o \
	binomial_coeffs.o \
	borsuk_lower_bound.o \
	brent.o \
	chebyshev_points.o \
	compfunc_kernel.o \
	compute_a_and_b_matrices.o \
	compute_a_matrix.o \
	constants.o \
	eigen_rankn_kernel.o \
	eigen_rankn_kernel_of_params.o \
	eigen_rankn_params.o \
	factorial.o \
	falling_factorial.o \
	find_all_zeros.o \
	find_rel_optima.o \
	hermite_polynomial.o \
	integral_kernel_disc.o \
	integral_kernel_measure.o \
	integral_kernel_singlevar.o \
	integral_neigen_disc.o \
	integral_neigen_svar.o \
	integral_nmonom_disc.o \
	integral_nmonom_svar.o \
	integral_nsect_disc.o \
	integral_nsect_svar.o \
	integral_rankn_svar.o \
	itoa.o \
	kernel.o \
	kernel_bachelier.o \
	kernel_blackscholes.o \
	kernel_cauchy.o \
	kernel_expprod.o \
	kernel_gaussian.o \
	kernel_neigen.o \
	kernel_nmonom.o \
	kernel_nsect.o \
	kernel_proc_ptr.o \
	kernel_summable.o \
	linear_combo_kernel.o \
	monomial.o \
	moore_penrose_inverse.o \
	mrgrnk.o \
	normal_distn.o \
	num_opt_rankn_kernel_asymm.o \
	num_opt_rankn_kernel_of_params.o \
	num_opt_rankn_params.o \
	option_formulae.o \
	quicksort.o \
	remez_step.o \
	remez_variant.o \
	set_precision.o \
	singlevar_func.o \
	singlevar_proc_ptr.o \
	taylor_series_rankn_kernel.o \
	taylor_series_rankn_kernel_of_params.o \
	taylor_series_rankn_params.o \
	tk_simple_lapack.o \
	unirnk.o \
	worst_rho_and_gamma.o

#Prospective Module files
NI_MODS =	
#Fortran Information files
NI_FIFS =	 \
	all_num_opt_mats_asymm.fif \
	binomial_coeffs.fif \
	borsuk_lower_bound.fif \
	brent.fif \
	chebyshev_points.fif \
	compfunc_kernel.fif \
	compute_a_and_b_matrices.fif \
	compute_a_matrix.fif \
	constants.fif \
	eigen_rankn_kernel.fif \
	eigen_rankn_kernel_of_params.fif \
	eigen_rankn_params.fif \
	factorial.fif \
	falling_factorial.fif \
	find_all_zeros.fif \
	find_rel_optima.fif \
	hermite_polynomial.fif \
	integral_kernel_disc.fif \
	integral_kernel_measure.fif \
	integral_kernel_singlevar.fif \
	integral_neigen_disc.fif \
	integral_neigen_svar.fif \
	integral_nmonom_disc.fif \
	integral_nmonom_svar.fif \
	integral_nsect_disc.fif \
	integral_nsect_svar.fif \
	integral_rankn_svar.fif \
	itoa.fif \
	kernel.fif \
	kernel_bachelier.fif \
	kernel_blackscholes.fif \
	kernel_cauchy.fif \
	kernel_expprod.fif \
	kernel_gaussian.fif \
	kernel_neigen.fif \
	kernel_nmonom.fif \
	kernel_nsect.fif \
	kernel_proc_ptr.fif \
	kernel_summable.fif \
	linear_combo_kernel.fif \
	monomial.fif \
	moore_penrose_inverse.fif \
	mrgrnk.fif \
	normal_distn.fif \
	num_opt_rankn_kernel_asymm.fif \
	num_opt_rankn_kernel_of_params.fif \
	num_opt_rankn_params.fif \
	option_formulae.fif \
	quicksort.fif \
	remez_step.fif \
	remez_variant.fif \
	set_precision.fif \
	singlevar_func.fif \
	singlevar_proc_ptr.fif \
	taylor_series_rankn_kernel.fif \
	taylor_series_rankn_kernel_of_params.fif \
	taylor_series_rankn_params.fif \
	tk_simple_lapack.fif \
	unirnk.fif \
	worst_rho_and_gamma.fif

#Library files
NI_LIBS = 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_rt.dll' 

#Dependencies

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -Wl,-shared -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseNagDLL.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)


#Other rules
all_num_opt_mats_asymm.o:
	@echo @nagfor all_num_opt_mats_asymm.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) all_num_opt_mats_asymm.fif -c ../all_num_opt_mats_asymm.f90
binomial_coeffs.o:
	@echo @nagfor binomial_coeffs.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) binomial_coeffs.fif -c ../binomial_coeffs.f90
borsuk_lower_bound.o:
	@echo @nagfor borsuk_lower_bound.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) borsuk_lower_bound.fif -c ../borsuk_lower_bound.f90
brent.o:
	@echo @nagfor brent.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) brent.fif -c ../brent.f90
chebyshev_points.o:
	@echo @nagfor chebyshev_points.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) chebyshev_points.fif -c ../chebyshev_points.f90
compfunc_kernel.o:
	@echo @nagfor compfunc_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) compfunc_kernel.fif -c ../compfunc_kernel.f90
compute_a_and_b_matrices.o:
	@echo @nagfor compute_a_and_b_matrices.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) compute_a_and_b_matrices.fif -c ../compute_a_and_b_matrices.f90
compute_a_matrix.o:
	@echo @nagfor compute_a_matrix.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) compute_a_matrix.fif -c ../compute_a_matrix.f90
constants.o:
	@echo @nagfor constants.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) constants.fif -c ../constants.f90
eigen_rankn_kernel.o:
	@echo @nagfor eigen_rankn_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) eigen_rankn_kernel.fif -c ../eigen_rankn_kernel.f90
eigen_rankn_kernel_of_params.o:
	@echo @nagfor eigen_rankn_kernel_of_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) eigen_rankn_kernel_of_params.fif -c ../eigen_rankn_kernel_of_params.f90
eigen_rankn_params.o:
	@echo @nagfor eigen_rankn_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) eigen_rankn_params.fif -c ../eigen_rankn_params.f90
factorial.o:
	@echo @nagfor factorial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) factorial.fif -c ../factorial.f90
falling_factorial.o:
	@echo @nagfor falling_factorial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) falling_factorial.fif -c ../falling_factorial.f90
find_all_zeros.o:
	@echo @nagfor find_all_zeros.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) find_all_zeros.fif -c ../find_all_zeros.f90
find_rel_optima.o:
	@echo @nagfor find_rel_optima.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) find_rel_optima.fif -c ../find_rel_optima.f90
hermite_polynomial.o:
	@echo @nagfor hermite_polynomial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) hermite_polynomial.fif -c ../hermite_polynomial.f90
integral_kernel_disc.o:
	@echo @nagfor integral_kernel_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_kernel_disc.fif -c ../integral_kernel_disc.f90
integral_kernel_measure.o:
	@echo @nagfor integral_kernel_measure.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_kernel_measure.fif -c ../integral_kernel_measure.f90
integral_kernel_singlevar.o:
	@echo @nagfor integral_kernel_singlevar.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_kernel_singlevar.fif -c ../integral_kernel_singlevar.f90
integral_neigen_disc.o:
	@echo @nagfor integral_neigen_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_neigen_disc.fif -c ../integral_neigen_disc.f90
integral_neigen_svar.o:
	@echo @nagfor integral_neigen_svar.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_neigen_svar.fif -c ../integral_neigen_svar.f90
integral_nmonom_disc.o:
	@echo @nagfor integral_nmonom_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_nmonom_disc.fif -c ../integral_nmonom_disc.f90
integral_nmonom_svar.o:
	@echo @nagfor integral_nmonom_svar.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_nmonom_svar.fif -c ../integral_nmonom_svar.f90
integral_nsect_disc.o:
	@echo @nagfor integral_nsect_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_nsect_disc.fif -c ../integral_nsect_disc.f90
integral_nsect_svar.o:
	@echo @nagfor integral_nsect_svar.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_nsect_svar.fif -c ../integral_nsect_svar.f90
integral_rankn_svar.o:
	@echo @nagfor integral_rankn_svar.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) integral_rankn_svar.fif -c ../integral_rankn_svar.f90
itoa.o:
	@echo @nagfor itoa.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) itoa.fif -c ../itoa.f90
kernel.o:
	@echo @nagfor kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel.fif -c ../kernel.f90
kernel_bachelier.o:
	@echo @nagfor kernel_bachelier.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_bachelier.fif -c ../kernel_bachelier.f90
kernel_blackscholes.o:
	@echo @nagfor kernel_blackscholes.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_blackscholes.fif -c ../kernel_blackscholes.f90
kernel_cauchy.o:
	@echo @nagfor kernel_cauchy.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_cauchy.fif -c ../kernel_cauchy.f90
kernel_expprod.o:
	@echo @nagfor kernel_expprod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_expprod.fif -c ../kernel_expprod.f90
kernel_gaussian.o:
	@echo @nagfor kernel_gaussian.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_gaussian.fif -c ../kernel_gaussian.f90
kernel_neigen.o:
	@echo @nagfor kernel_neigen.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_neigen.fif -c ../kernel_neigen.f90
kernel_nmonom.o:
	@echo @nagfor kernel_nmonom.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_nmonom.fif -c ../kernel_nmonom.f90
kernel_nsect.o:
	@echo @nagfor kernel_nsect.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_nsect.fif -c ../kernel_nsect.f90
kernel_proc_ptr.o:
	@echo @nagfor kernel_proc_ptr.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_proc_ptr.fif -c ../kernel_proc_ptr.f90
kernel_summable.o:
	@echo @nagfor kernel_summable.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_summable.fif -c ../kernel_summable.f90
linear_combo_kernel.o:
	@echo @nagfor linear_combo_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) linear_combo_kernel.fif -c ../linear_combo_kernel.f90
monomial.o:
	@echo @nagfor monomial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) monomial.fif -c ../monomial.f90
moore_penrose_inverse.o:
	@echo @nagfor moore_penrose_inverse.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) moore_penrose_inverse.fif -c ../moore_penrose_inverse.f90
mrgrnk.o:
	@echo @nagfor mrgrnk.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) mrgrnk.fif -c ../mrgrnk.f90
normal_distn.o:
	@echo @nagfor normal_distn.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) normal_distn.fif -c ../normal_distn.f90
num_opt_rankn_kernel_asymm.o:
	@echo @nagfor num_opt_rankn_kernel_asymm.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) num_opt_rankn_kernel_asymm.fif -c ../num_opt_rankn_kernel_asymm.f90
num_opt_rankn_kernel_of_params.o:
	@echo @nagfor num_opt_rankn_kernel_of_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) num_opt_rankn_kernel_of_params.fif -c ../num_opt_rankn_kernel_of_params.f90
num_opt_rankn_params.o:
	@echo @nagfor num_opt_rankn_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) num_opt_rankn_params.fif -c ../num_opt_rankn_params.f90
option_formulae.o:
	@echo @nagfor option_formulae.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) option_formulae.fif -c ../option_formulae.f90
quicksort.o:
	@echo @nagfor quicksort.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) quicksort.fif -c ../quicksort.f90
remez_step.o:
	@echo @nagfor remez_step.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) remez_step.fif -c ../remez_step.f90
remez_variant.o:
	@echo @nagfor remez_variant.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) remez_variant.fif -c ../remez_variant.f90
set_precision.o:
	@echo @nagfor set_precision.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) set_precision.fif -c ../set_precision.f90
singlevar_func.o:
	@echo @nagfor singlevar_func.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) singlevar_func.fif -c ../singlevar_func.f90
singlevar_proc_ptr.o:
	@echo @nagfor singlevar_proc_ptr.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) singlevar_proc_ptr.fif -c ../singlevar_proc_ptr.f90
taylor_series_rankn_kernel.o:
	@echo @nagfor taylor_series_rankn_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) taylor_series_rankn_kernel.fif -c ../taylor_series_rankn_kernel.f90
taylor_series_rankn_kernel_of_params.o:
	@echo @nagfor taylor_series_rankn_kernel_of_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) taylor_series_rankn_kernel_of_params.fif -c ../taylor_series_rankn_kernel_of_params.f90
taylor_series_rankn_params.o:
	@echo @nagfor taylor_series_rankn_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) taylor_series_rankn_params.fif -c ../taylor_series_rankn_params.f90
tk_simple_lapack.o:
	@echo @nagfor tk_simple_lapack.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) tk_simple_lapack.fif -c ../tk_simple_lapack.f90
unirnk.o:
	@echo @nagfor unirnk.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) unirnk.fif -c ../unirnk.f90
worst_rho_and_gamma.o:
	@echo @nagfor worst_rho_and_gamma.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) worst_rho_and_gamma.fif -c ../worst_rho_and_gamma.f90

#Rebuild rule
all:clean $(NI_TARGET)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) all_num_opt_mats_asymm.o binomial_coeffs.o borsuk_lower_bound.o brent.o chebyshev_points.o compfunc_kernel.o compute_a_and_b_matrices.o compute_a_matrix.o constants.o eigen_rankn_kernel.o
	$(NI_RM) eigen_rankn_kernel_of_params.o eigen_rankn_params.o factorial.o falling_factorial.o find_all_zeros.o find_rel_optima.o hermite_polynomial.o integral_kernel_disc.o integral_kernel_measure.o integral_kernel_singlevar.o
	$(NI_RM) integral_neigen_disc.o integral_neigen_svar.o integral_nmonom_disc.o integral_nmonom_svar.o integral_nsect_disc.o integral_nsect_svar.o integral_rankn_svar.o itoa.o kernel.o kernel_bachelier.o
	$(NI_RM) kernel_blackscholes.o kernel_cauchy.o kernel_expprod.o kernel_gaussian.o kernel_neigen.o kernel_nmonom.o kernel_nsect.o kernel_proc_ptr.o kernel_summable.o linear_combo_kernel.o
	$(NI_RM) monomial.o moore_penrose_inverse.o mrgrnk.o normal_distn.o num_opt_rankn_kernel_asymm.o num_opt_rankn_kernel_of_params.o num_opt_rankn_params.o option_formulae.o quicksort.o remez_step.o
	$(NI_RM) remez_variant.o set_precision.o singlevar_func.o singlevar_proc_ptr.o taylor_series_rankn_kernel.o taylor_series_rankn_kernel_of_params.o taylor_series_rankn_params.o tk_simple_lapack.o unirnk.o worst_rho_and_gamma.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) all_num_opt_mats_asymm.fif binomial_coeffs.fif borsuk_lower_bound.fif brent.fif chebyshev_points.fif compfunc_kernel.fif compute_a_and_b_matrices.fif compute_a_matrix.fif constants.fif eigen_rankn_kernel.fif
	$(NI_RM) eigen_rankn_kernel_of_params.fif eigen_rankn_params.fif factorial.fif falling_factorial.fif find_all_zeros.fif find_rel_optima.fif hermite_polynomial.fif integral_kernel_disc.fif integral_kernel_measure.fif integral_kernel_singlevar.fif
	$(NI_RM) integral_neigen_disc.fif integral_neigen_svar.fif integral_nmonom_disc.fif integral_nmonom_svar.fif integral_nsect_disc.fif integral_nsect_svar.fif integral_rankn_svar.fif itoa.fif kernel.fif kernel_bachelier.fif
	$(NI_RM) kernel_blackscholes.fif kernel_cauchy.fif kernel_expprod.fif kernel_gaussian.fif kernel_neigen.fif kernel_nmonom.fif kernel_nsect.fif kernel_proc_ptr.fif kernel_summable.fif linear_combo_kernel.fif
	$(NI_RM) monomial.fif moore_penrose_inverse.fif mrgrnk.fif normal_distn.fif num_opt_rankn_kernel_asymm.fif num_opt_rankn_kernel_of_params.fif num_opt_rankn_params.fif option_formulae.fif quicksort.fif remez_step.fif
	$(NI_RM) remez_variant.fif set_precision.fif singlevar_func.fif singlevar_proc_ptr.fif taylor_series_rankn_kernel.fif taylor_series_rankn_kernel_of_params.fif taylor_series_rankn_params.fif tk_simple_lapack.fif unirnk.fif worst_rho_and_gamma.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
