#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -compatible -g -C=all
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -compatible -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = -I../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_LibPath = -L'../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib64' -L$(fblib) -L'../../../../../../../../Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/mkl' -L../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL 
NI_LDFLAGS = 
NI_Link = nagfor
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#def file
NI_DEF = KernelyzeBaseBindCNagDLL.def

#Output file
NI_OUTPUT = KernelyzeBaseBindCNagDLL.dll

#Target name
NI_TARGET = KernelyzeBaseBindCNagDLL.dll

#Object files
NI_OBJS =	 \
	fort_c_interop.o \
	borsuk_lower_bound_for_c.o \
	brent_for_c.o \
	chebyshev_points_for_c.o \
	eigen_funcs_for_c.o \
	find_all_zeros_for_c.o \
	find_rel_optima_for_c.o \
	kernel_integral_eval_for_c.o \
	linear_solve_for_c.o \
	matmul_for_c.o \
	mp_inverse_for_c.o \
	num_opt_funcs_for_c.o \
	option_formulae_for_c.o \
	taylor_funcs_for_c.o \
	worst_rho_and_gamma_for_c.o

#Depend Object files
NI_DOBJS =	 \
	fort_c_interop.o \
	borsuk_lower_bound_for_c.o \
	brent_for_c.o \
	chebyshev_points_for_c.o \
	eigen_funcs_for_c.o \
	find_all_zeros_for_c.o \
	find_rel_optima_for_c.o \
	kernel_integral_eval_for_c.o \
	linear_solve_for_c.o \
	matmul_for_c.o \
	mp_inverse_for_c.o \
	num_opt_funcs_for_c.o \
	option_formulae_for_c.o \
	taylor_funcs_for_c.o \
	worst_rho_and_gamma_for_c.o

#Prospective Module files
NI_MODS =	 \
    'borsuk_lower_bound_for_c_mod.mod' \
    'brent_for_c_mod.mod' \
    'chebyshev_points_for_c_mod.mod' \
    'eigen_funcs_for_c_mod.mod' \
    'find_all_zeros_for_c_mod.mod' \
    'find_rel_optima_for_c_mod.mod' \
    'fort_c_interop_mod.mod' \
    'kernel_integral_eval_for_c_mod.mod' \
    'linear_solve_for_c_mod.mod' \
    'matmul_for_c_mod.mod' \
    'mp_inverse_for_c_mod.mod' \
    'num_opt_funcs_for_c_mod.mod' \
    'option_formulae_for_c_mod.mod' \
    'taylor_funcs_for_c_mod.mod' \
    'worst_rho_and_gamma_for_c_mod.mod'

#Fortran Information files
NI_FIFS =	 \
	fort_c_interop.fif \
	borsuk_lower_bound_for_c.fif \
	brent_for_c.fif \
	chebyshev_points_for_c.fif \
	eigen_funcs_for_c.fif \
	find_all_zeros_for_c.fif \
	find_rel_optima_for_c.fif \
	kernel_integral_eval_for_c.fif \
	linear_solve_for_c.fif \
	matmul_for_c.fif \
	mp_inverse_for_c.fif \
	num_opt_funcs_for_c.fif \
	option_formulae_for_c.fif \
	taylor_funcs_for_c.fif \
	worst_rho_and_gamma_for_c.fif

#Library files
NI_LIBS = 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_rt.dll' ../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/KernelyzeBaseNagDLL.dll 

#Dependencies
NI_EQ==
NI_SC=\;
borsuk_lower_bound_for_c.o:	../borsuk_lower_bound_for_c.f90
borsuk_lower_bound_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
borsuk_lower_bound_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
borsuk_lower_bound_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/borsuk_lower_bound_mod.mod
borsuk_lower_bound_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
borsuk_lower_bound_for_c.o:	fort_c_interop_mod.mod
borsuk_lower_bound_for_c_mod.mod:	../borsuk_lower_bound_for_c.f90
borsuk_lower_bound_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
borsuk_lower_bound_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
borsuk_lower_bound_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/borsuk_lower_bound_mod.mod
borsuk_lower_bound_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
borsuk_lower_bound_for_c_mod.mod:	fort_c_interop_mod.mod
brent_for_c.o:	../brent_for_c.f90
brent_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
brent_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
brent_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/brent_mod.mod
brent_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
brent_for_c.o:	fort_c_interop_mod.mod
brent_for_c_mod.mod:	../brent_for_c.f90
brent_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
brent_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
brent_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/brent_mod.mod
brent_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
brent_for_c_mod.mod:	fort_c_interop_mod.mod
chebyshev_points_for_c.o:	../chebyshev_points_for_c.f90
chebyshev_points_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
chebyshev_points_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
chebyshev_points_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
chebyshev_points_for_c_mod.mod:	../chebyshev_points_for_c.f90
chebyshev_points_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
chebyshev_points_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
chebyshev_points_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
eigen_funcs_for_c.o:	../eigen_funcs_for_c.f90
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
eigen_funcs_for_c.o:	fort_c_interop_mod.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_neigen_mod.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_params_mod.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_kernel_of_params_mod.mod
eigen_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_neigen_disc_mod.mod
eigen_funcs_for_c_mod.mod:	../eigen_funcs_for_c.f90
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
eigen_funcs_for_c_mod.mod:	fort_c_interop_mod.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_neigen_mod.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_params_mod.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_kernel_of_params_mod.mod
eigen_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_neigen_disc_mod.mod
find_all_zeros_for_c.o:	../find_all_zeros_for_c.f90
find_all_zeros_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
find_all_zeros_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
find_all_zeros_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
find_all_zeros_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
find_all_zeros_for_c.o:	fort_c_interop_mod.mod
find_all_zeros_for_c_mod.mod:	../find_all_zeros_for_c.f90
find_all_zeros_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
find_all_zeros_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
find_all_zeros_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
find_all_zeros_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
find_all_zeros_for_c_mod.mod:	fort_c_interop_mod.mod
find_rel_optima_for_c.o:	../find_rel_optima_for_c.f90
find_rel_optima_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
find_rel_optima_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
find_rel_optima_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
find_rel_optima_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
find_rel_optima_for_c.o:	fort_c_interop_mod.mod
find_rel_optima_for_c_mod.mod:	../find_rel_optima_for_c.f90
find_rel_optima_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
find_rel_optima_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
find_rel_optima_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
find_rel_optima_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
find_rel_optima_for_c_mod.mod:	fort_c_interop_mod.mod
fort_c_interop.o:	../fort_c_interop.f90
fort_c_interop_mod.mod:	../fort_c_interop.f90
kernel_integral_eval_for_c.o:	../kernel_integral_eval_for_c.f90
kernel_integral_eval_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
kernel_integral_eval_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
kernel_integral_eval_for_c.o:	fort_c_interop_mod.mod
kernel_integral_eval_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
kernel_integral_eval_for_c_mod.mod:	../kernel_integral_eval_for_c.f90
kernel_integral_eval_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
kernel_integral_eval_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
kernel_integral_eval_for_c_mod.mod:	fort_c_interop_mod.mod
kernel_integral_eval_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
linear_solve_for_c.o:	../linear_solve_for_c.f90
linear_solve_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
linear_solve_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
linear_solve_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/tk_simple_lapack_mod.mod
linear_solve_for_c_mod.mod:	../linear_solve_for_c.f90
linear_solve_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
linear_solve_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
linear_solve_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/tk_simple_lapack_mod.mod
matmul_for_c.o:	../matmul_for_c.f90
matmul_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
matmul_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
matmul_for_c_mod.mod:	../matmul_for_c.f90
matmul_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
matmul_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
mp_inverse_for_c.o:	../mp_inverse_for_c.f90
mp_inverse_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
mp_inverse_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/moore_penrose_inverse_mod.mod
mp_inverse_for_c_mod.mod:	../mp_inverse_for_c.f90
mp_inverse_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
mp_inverse_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/moore_penrose_inverse_mod.mod
num_opt_funcs_for_c.o:	../num_opt_funcs_for_c.f90
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
num_opt_funcs_for_c.o:	fort_c_interop_mod.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_params_mod.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_of_params_mod.mod
num_opt_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nsect_disc_mod.mod
num_opt_funcs_for_c_mod.mod:	../num_opt_funcs_for_c.f90
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
num_opt_funcs_for_c_mod.mod:	fort_c_interop_mod.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_params_mod.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_of_params_mod.mod
num_opt_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nsect_disc_mod.mod
option_formulae_for_c.o:	../option_formulae_for_c.f90
option_formulae_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
option_formulae_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
option_formulae_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/option_formulae_mod.mod
option_formulae_for_c.o:	fort_c_interop_mod.mod
option_formulae_for_c_mod.mod:	../option_formulae_for_c.f90
option_formulae_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
option_formulae_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
option_formulae_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/option_formulae_mod.mod
option_formulae_for_c_mod.mod:	fort_c_interop_mod.mod
taylor_funcs_for_c.o:	../taylor_funcs_for_c.f90
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
taylor_funcs_for_c.o:	fort_c_interop_mod.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nmonom_mod.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_params_mod.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_kernel_of_params_mod.mod
taylor_funcs_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nmonom_disc_mod.mod
taylor_funcs_for_c_mod.mod:	../taylor_funcs_for_c.f90
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
taylor_funcs_for_c_mod.mod:	fort_c_interop_mod.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nmonom_mod.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_params_mod.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_kernel_of_params_mod.mod
taylor_funcs_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nmonom_disc_mod.mod
worst_rho_and_gamma_for_c.o:	../worst_rho_and_gamma_for_c.f90
worst_rho_and_gamma_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
worst_rho_and_gamma_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
worst_rho_and_gamma_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod
worst_rho_and_gamma_for_c.o:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
worst_rho_and_gamma_for_c.o:	fort_c_interop_mod.mod
worst_rho_and_gamma_for_c_mod.mod:	../worst_rho_and_gamma_for_c.f90
worst_rho_and_gamma_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
worst_rho_and_gamma_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
worst_rho_and_gamma_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod
worst_rho_and_gamma_for_c_mod.mod:	../../../KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_proc_ptr_mod.mod
worst_rho_and_gamma_for_c_mod.mod:	fort_c_interop_mod.mod

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -Wl,-shared -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseBindCNagDLL.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)


#Other rules
fort_c_interop.o:
	@echo @nagfor fort_c_interop.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) fort_c_interop.fif -c ../fort_c_interop.f90
borsuk_lower_bound_for_c.o:
	@echo @nagfor borsuk_lower_bound_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) borsuk_lower_bound_for_c.fif -c ../borsuk_lower_bound_for_c.f90
brent_for_c.o:
	@echo @nagfor brent_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) brent_for_c.fif -c ../brent_for_c.f90
chebyshev_points_for_c.o:
	@echo @nagfor chebyshev_points_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) chebyshev_points_for_c.fif -c ../chebyshev_points_for_c.f90
eigen_funcs_for_c.o:
	@echo @nagfor eigen_funcs_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) eigen_funcs_for_c.fif -c ../eigen_funcs_for_c.f90
find_all_zeros_for_c.o:
	@echo @nagfor find_all_zeros_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) find_all_zeros_for_c.fif -c ../find_all_zeros_for_c.f90
find_rel_optima_for_c.o:
	@echo @nagfor find_rel_optima_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) find_rel_optima_for_c.fif -c ../find_rel_optima_for_c.f90
kernel_integral_eval_for_c.o:
	@echo @nagfor kernel_integral_eval_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_integral_eval_for_c.fif -c ../kernel_integral_eval_for_c.f90
linear_solve_for_c.o:
	@echo @nagfor linear_solve_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) linear_solve_for_c.fif -c ../linear_solve_for_c.f90
matmul_for_c.o:
	@echo @nagfor matmul_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) matmul_for_c.fif -c ../matmul_for_c.f90
mp_inverse_for_c.o:
	@echo @nagfor mp_inverse_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) mp_inverse_for_c.fif -c ../mp_inverse_for_c.f90
num_opt_funcs_for_c.o:
	@echo @nagfor num_opt_funcs_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) num_opt_funcs_for_c.fif -c ../num_opt_funcs_for_c.f90
option_formulae_for_c.o:
	@echo @nagfor option_formulae_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) option_formulae_for_c.fif -c ../option_formulae_for_c.f90
taylor_funcs_for_c.o:
	@echo @nagfor taylor_funcs_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) taylor_funcs_for_c.fif -c ../taylor_funcs_for_c.f90
worst_rho_and_gamma_for_c.o:
	@echo @nagfor worst_rho_and_gamma_for_c.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) worst_rho_and_gamma_for_c.fif -c ../worst_rho_and_gamma_for_c.f90

#Rebuild rule
all:clean $(NI_TARGET)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) fort_c_interop.o borsuk_lower_bound_for_c.o brent_for_c.o chebyshev_points_for_c.o eigen_funcs_for_c.o find_all_zeros_for_c.o find_rel_optima_for_c.o kernel_integral_eval_for_c.o linear_solve_for_c.o matmul_for_c.o
	$(NI_RM) mp_inverse_for_c.o num_opt_funcs_for_c.o option_formulae_for_c.o taylor_funcs_for_c.o worst_rho_and_gamma_for_c.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) fort_c_interop.fif borsuk_lower_bound_for_c.fif brent_for_c.fif chebyshev_points_for_c.fif eigen_funcs_for_c.fif find_all_zeros_for_c.fif find_rel_optima_for_c.fif kernel_integral_eval_for_c.fif linear_solve_for_c.fif matmul_for_c.fif
	$(NI_RM) mp_inverse_for_c.fif num_opt_funcs_for_c.fif option_formulae_for_c.fif taylor_funcs_for_c.fif worst_rho_and_gamma_for_c.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
