#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -free -C=all
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = -I../../../../KernelyzeLibs/KernelyzeBaseBindC/KernelyzeBaseBindC/KernelyzeBaseBindCNagDLL 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib64' -L$(fblib) -L'../../../../../../../../Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/mkl' -L../../../../KernelyzeLibs/KernelyzeBaseBindC/KernelyzeBaseBindC/KernelyzeBaseBindCNagDLL 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .cpp .o 

#Output file
NI_OUTPUT = KernelyzeBaseBindCTestsNag.exe

#Target name
NI_TARGET = KernelyzeBaseBindCTestsNag.exe

#Object files
NI_OBJS =	 \
	borsuk_lower_bound_test.o \
	brent_test.o \
	eigen_approx_test.o \
	find_all_zeros_test.o \
	find_rel_optima_test.o \
	kernel_integral_eval_test.o \
	KernelyzeBaseBindCTests.o \
	linear_solve_test.o \
	matmul_test.o \
	num_opt_funcs_test.o \
	option_formulae_test.o \
	taylor_approx_test.o \
	test_function_ptrs.o \
	worst_rho_and_gamma_test.o \
	stdafx.o

#Depend Object files
NI_DOBJS =	 \
	borsuk_lower_bound_test.o \
	brent_test.o \
	eigen_approx_test.o \
	find_all_zeros_test.o \
	find_rel_optima_test.o \
	kernel_integral_eval_test.o \
	KernelyzeBaseBindCTests.o \
	linear_solve_test.o \
	matmul_test.o \
	num_opt_funcs_test.o \
	option_formulae_test.o \
	taylor_approx_test.o \
	test_function_ptrs.o \
	worst_rho_and_gamma_test.o \
	stdafx.o

#Prospective Module files
NI_MODS =	
#Fortran Information files
NI_FIFS =	

#Library files
NI_LIBS = 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_rt.dll' 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_core.dll' 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_intel_thread.dll' C:\Users\thoma\Documents\Kernelyze\KernelyzeLibs\KernelyzeBaseBindC\KernelyzeBaseBindC\KernelyzeBaseBindCNagDLL\KernelyzeBaseBindCNagDLL.dll -lstdc++ 

#Dependencies
NI_EQ==
NI_SC=\;
borsuk_lower_bound_test.o: ..\borsuk_lower_bound_test.cpp \
 ..\/test_function_ptrs.h ..\/borsuk_lower_bound_test.h
brent_test.o: ..\brent_test.cpp ..\/brent_test.h
eigen_approx_test.o: ..\eigen_approx_test.cpp ..\/test_function_ptrs.h \
 ..\/eigen_approx_test.h
find_all_zeros_test.o: ..\find_all_zeros_test.cpp \
 ..\/find_all_zeros_test.h
find_rel_optima_test.o: ..\find_rel_optima_test.cpp \
 ..\/find_rel_optima_test.h
kernel_integral_eval_test.o: ..\kernel_integral_eval_test.cpp \
 ..\/test_function_ptrs.h ..\/kernel_integral_eval_test.h
KernelyzeBaseBindCTests.o: ..\KernelyzeBaseBindCTests.cpp ..\/stdafx.h \
 ..\/targetver.h ..\/mp_inverse.h ..\/num_opt_funcs_test.h \
 ..\/brent_test.h ..\/find_all_zeros_test.h ..\/find_rel_optima_test.h \
 ..\/borsuk_lower_bound_test.h ..\/worst_rho_and_gamma_test.h \
 ..\/taylor_approx_test.h ..\/eigen_approx_test.h \
 ..\/kernel_integral_eval_test.h ..\/option_formulae_test.h \
 ..\/linear_solve_test.h ..\/matmul_test.h
linear_solve_test.o: ..\linear_solve_test.cpp ..\/matmul_test.h \
 ..\/linear_solve_test.h
matmul_test.o: ..\matmul_test.cpp ..\/matmul_test.h
num_opt_funcs_test.o: ..\num_opt_funcs_test.cpp ..\/test_function_ptrs.h \
 ..\/num_opt_funcs_test.h
option_formulae_test.o: ..\option_formulae_test.cpp \
 ..\/option_formulae_test.h
taylor_approx_test.o: ..\taylor_approx_test.cpp ..\/test_function_ptrs.h \
 ..\/taylor_approx_test.h
test_function_ptrs.o: ..\test_function_ptrs.cpp ..\/test_function_ptrs.h \
 ..\/option_formulae_test.h
worst_rho_and_gamma_test.o: ..\worst_rho_and_gamma_test.cpp \
 ..\/test_function_ptrs.h ..\/worst_rho_and_gamma_test.h
stdafx.o: ..\stdafx.cpp ..\/stdafx.h ..\/targetver.h

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseBindCTestsNag.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
borsuk_lower_bound_test.o:
	@echo @cc borsuk_lower_bound_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../borsuk_lower_bound_test.cpp
brent_test.o:
	@echo @cc brent_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../brent_test.cpp
eigen_approx_test.o:
	@echo @cc eigen_approx_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../eigen_approx_test.cpp
find_all_zeros_test.o:
	@echo @cc find_all_zeros_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../find_all_zeros_test.cpp
find_rel_optima_test.o:
	@echo @cc find_rel_optima_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../find_rel_optima_test.cpp
kernel_integral_eval_test.o:
	@echo @cc kernel_integral_eval_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../kernel_integral_eval_test.cpp
KernelyzeBaseBindCTests.o:
	@echo @cc KernelyzeBaseBindCTests.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../KernelyzeBaseBindCTests.cpp
linear_solve_test.o:
	@echo @cc linear_solve_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../linear_solve_test.cpp
matmul_test.o:
	@echo @cc matmul_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../matmul_test.cpp
num_opt_funcs_test.o:
	@echo @cc num_opt_funcs_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../num_opt_funcs_test.cpp
option_formulae_test.o:
	@echo @cc option_formulae_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../option_formulae_test.cpp
taylor_approx_test.o:
	@echo @cc taylor_approx_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../taylor_approx_test.cpp
test_function_ptrs.o:
	@echo @cc test_function_ptrs.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../test_function_ptrs.cpp
worst_rho_and_gamma_test.o:
	@echo @cc worst_rho_and_gamma_test.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../worst_rho_and_gamma_test.cpp
stdafx.o:
	@echo @cc stdafx.cpp
	$(NI_CPP_Compiler) $(NI_IFLAGS) $(NI_C_CompOpts) -c ../stdafx.cpp

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseBindCTestsNag.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) borsuk_lower_bound_test.o brent_test.o eigen_approx_test.o find_all_zeros_test.o find_rel_optima_test.o kernel_integral_eval_test.o KernelyzeBaseBindCTests.o linear_solve_test.o matmul_test.o num_opt_funcs_test.o
	$(NI_RM) option_formulae_test.o taylor_approx_test.o test_function_ptrs.o worst_rho_and_gamma_test.o stdafx.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
