#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -free -C=all
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = -I../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../../../Program Files (x86)/NAG/EFBuilder 6.1/lib64' -L$(fblib) -L'../../../../../../../../Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/mkl' -L../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = KernelyzeBaseTestsNag.exe

#Target name
NI_TARGET = KernelyzeBaseTestsNag.exe

#Object files
NI_OBJS =	 \
	intrinsic_test_funcs.o \
	kernel_test_funcs.o \
	test_set_precision.o \
	test_constants.o \
	test_elemental.o \
	test_unirnk.o \
	test_mrgrnk.o \
	test_quicksort.o \
	test_binomial_coeffs.o \
	test_factorial.o \
	test_falling_factorial.o \
	test_hermite_polynomial.o \
	test_singlevar_proc_ptr.o \
	test_brent.o \
	test_moore_penrose_inverse.o \
	test_compute_a_matrix.o \
	test_compute_a_and_b_matrices.o \
	test_find_all_zeros.o \
	test_find_rel_optima.o \
	test_chebyshev_points.o \
	test_remez_step.o \
	test_borsuk_lower_bound.o \
	test_worst_rho_and_gamma.o \
	test_all_num_opt_mats_asymm.o \
	test_num_opt_rankn_kernel.o \
	test_num_opt_rankn_params.o \
	test_taylor_series_rankn_kernel.o \
	test_eigen_rankn_kernel.o \
	test_integral_kernel_disc.o \
	test_integral_rankn_disc.o \
	test_derivs.o \
	fort_approx.o

#Depend Object files
NI_DOBJS =	 \
	intrinsic_test_funcs.o \
	kernel_test_funcs.o \
	test_set_precision.o \
	test_constants.o \
	test_elemental.o \
	test_unirnk.o \
	test_mrgrnk.o \
	test_quicksort.o \
	test_binomial_coeffs.o \
	test_factorial.o \
	test_falling_factorial.o \
	test_hermite_polynomial.o \
	test_singlevar_proc_ptr.o \
	test_brent.o \
	test_moore_penrose_inverse.o \
	test_compute_a_matrix.o \
	test_compute_a_and_b_matrices.o \
	test_find_all_zeros.o \
	test_find_rel_optima.o \
	test_chebyshev_points.o \
	test_remez_step.o \
	test_borsuk_lower_bound.o \
	test_worst_rho_and_gamma.o \
	test_all_num_opt_mats_asymm.o \
	test_num_opt_rankn_kernel.o \
	test_num_opt_rankn_params.o \
	test_taylor_series_rankn_kernel.o \
	test_eigen_rankn_kernel.o \
	test_integral_kernel_disc.o \
	test_integral_rankn_disc.o \
	test_derivs.o \
	fort_approx.o

#Prospective Module files
NI_MODS =	 \
    'intrinsic_test_funcs_mod.mod' \
    'kernel_test_funcs_mod.mod' \
    'test_all_num_opt_mats_asymm_mod.mod' \
    'test_binomial_coeffs_mod.mod' \
    'test_borsuk_lower_bound_mod.mod' \
    'test_brent_mod.mod' \
    'test_chebyshev_points_mod.mod' \
    'test_compute_a_and_b_matrices_mod.mod' \
    'test_compute_a_matrix_mod.mod' \
    'test_constants_mod.mod' \
    'test_derivs_mod.mod' \
    'test_eigen_rankn_kernel_mod.mod' \
    'test_elemental_mod.mod' \
    'test_factorial_mod.mod' \
    'test_falling_factorial_mod.mod' \
    'test_find_all_zeros_mod.mod' \
    'test_find_rel_optima_mod.mod' \
    'test_hermite_polynomial_mod.mod' \
    'test_integral_kernel_disc_mod.mod' \
    'test_integral_rankn_disc_mod.mod' \
    'test_moore_penrose_inverse_mod.mod' \
    'test_mrgrnk_mod.mod' \
    'test_num_opt_rankn_kernel_mod.mod' \
    'test_num_opt_rankn_params_mod.mod' \
    'test_quicksort_mod.mod' \
    'test_remez_step_mod.mod' \
    'test_set_precision_mod.mod' \
    'test_singlevar_proc_ptr_mod.mod' \
    'test_taylor_series_rankn_kernel_mod.mod' \
    'test_unirnk_mod.mod' \
    'test_worst_rho_and_gamma_mod.mod'

#Fortran Information files
NI_FIFS =	 \
	intrinsic_test_funcs.fif \
	kernel_test_funcs.fif \
	test_set_precision.fif \
	test_constants.fif \
	test_elemental.fif \
	test_unirnk.fif \
	test_mrgrnk.fif \
	test_quicksort.fif \
	test_binomial_coeffs.fif \
	test_factorial.fif \
	test_falling_factorial.fif \
	test_hermite_polynomial.fif \
	test_singlevar_proc_ptr.fif \
	test_brent.fif \
	test_moore_penrose_inverse.fif \
	test_compute_a_matrix.fif \
	test_compute_a_and_b_matrices.fif \
	test_find_all_zeros.fif \
	test_find_rel_optima.fif \
	test_chebyshev_points.fif \
	test_remez_step.fif \
	test_borsuk_lower_bound.fif \
	test_worst_rho_and_gamma.fif \
	test_all_num_opt_mats_asymm.fif \
	test_num_opt_rankn_kernel.fif \
	test_num_opt_rankn_params.fif \
	test_taylor_series_rankn_kernel.fif \
	test_eigen_rankn_kernel.fif \
	test_integral_kernel_disc.fif \
	test_integral_rankn_disc.fif \
	test_derivs.fif \
	fort_approx.fif

#Library files
NI_LIBS = 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_rt.dll' 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_core.dll' 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.4.246\windows\redist\intel64_win\mkl\mkl_intel_thread.dll' C:\Users\thoma\Documents\Kernelyze\KernelyzeLibs\KernelyzeBase\KernelyzeBase\KernelyzeBaseNagDLL\KernelyzeBaseNagDLL.dll 

#Dependencies
NI_EQ==
NI_SC=\;
fort_approx.o:	../fort_approx.f90
fort_approx.o:	intrinsic_test_funcs_mod.mod
fort_approx.o:	kernel_test_funcs_mod.mod
fort_approx.o:	test_set_precision_mod.mod
fort_approx.o:	test_constants_mod.mod
fort_approx.o:	test_elemental_mod.mod
fort_approx.o:	test_unirnk_mod.mod
fort_approx.o:	test_mrgrnk_mod.mod
fort_approx.o:	test_quicksort_mod.mod
fort_approx.o:	test_binomial_coeffs_mod.mod
fort_approx.o:	test_factorial_mod.mod
fort_approx.o:	test_falling_factorial_mod.mod
fort_approx.o:	test_hermite_polynomial_mod.mod
fort_approx.o:	test_singlevar_proc_ptr_mod.mod
fort_approx.o:	test_brent_mod.mod
fort_approx.o:	test_moore_penrose_inverse_mod.mod
fort_approx.o:	test_compute_a_matrix_mod.mod
fort_approx.o:	test_compute_a_and_b_matrices_mod.mod
fort_approx.o:	test_find_all_zeros_mod.mod
fort_approx.o:	test_find_rel_optima_mod.mod
fort_approx.o:	test_chebyshev_points_mod.mod
fort_approx.o:	test_remez_step_mod.mod
fort_approx.o:	test_borsuk_lower_bound_mod.mod
fort_approx.o:	test_worst_rho_and_gamma_mod.mod
fort_approx.o:	test_all_num_opt_mats_asymm_mod.mod
fort_approx.o:	test_num_opt_rankn_kernel_mod.mod
fort_approx.o:	test_num_opt_rankn_params_mod.mod
fort_approx.o:	test_taylor_series_rankn_kernel_mod.mod
fort_approx.o:	test_eigen_rankn_kernel_mod.mod
fort_approx.o:	test_integral_kernel_disc_mod.mod
fort_approx.o:	test_integral_rankn_disc_mod.mod
fort_approx.o:	test_derivs_mod.mod
intrinsic_test_funcs.o:	../intrinsic_test_funcs.f90
intrinsic_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
intrinsic_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
intrinsic_test_funcs_mod.mod:	../intrinsic_test_funcs.f90
intrinsic_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
intrinsic_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
kernel_test_funcs.o:	../kernel_test_funcs.f90
kernel_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
kernel_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
kernel_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
kernel_test_funcs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
kernel_test_funcs_mod.mod:	../kernel_test_funcs.f90
kernel_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
kernel_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
kernel_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
kernel_test_funcs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_all_num_opt_mats_asymm.o:	../test_all_num_opt_mats_asymm.f90
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod
test_all_num_opt_mats_asymm.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/all_num_opt_mats_asymm_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../test_all_num_opt_mats_asymm.f90
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod
test_all_num_opt_mats_asymm_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/all_num_opt_mats_asymm_mod.mod
test_binomial_coeffs.o:	../test_binomial_coeffs.f90
test_binomial_coeffs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_binomial_coeffs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/binomial_coeffs_mod.mod
test_binomial_coeffs_mod.mod:	../test_binomial_coeffs.f90
test_binomial_coeffs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_binomial_coeffs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/binomial_coeffs_mod.mod
test_borsuk_lower_bound.o:	../test_borsuk_lower_bound.f90
test_borsuk_lower_bound.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_borsuk_lower_bound.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_borsuk_lower_bound.o:	kernel_test_funcs_mod.mod
test_borsuk_lower_bound.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/borsuk_lower_bound_mod.mod
test_borsuk_lower_bound_mod.mod:	../test_borsuk_lower_bound.f90
test_borsuk_lower_bound_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_borsuk_lower_bound_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_borsuk_lower_bound_mod.mod:	kernel_test_funcs_mod.mod
test_borsuk_lower_bound_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/borsuk_lower_bound_mod.mod
test_brent.o:	../test_brent.f90
test_brent.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_brent.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/brent_mod.mod
test_brent.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_brent.o:	intrinsic_test_funcs_mod.mod
test_brent_mod.mod:	../test_brent.f90
test_brent_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_brent_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/brent_mod.mod
test_brent_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_brent_mod.mod:	intrinsic_test_funcs_mod.mod
test_chebyshev_points.o:	../test_chebyshev_points.f90
test_chebyshev_points.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_chebyshev_points.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_chebyshev_points_mod.mod:	../test_chebyshev_points.f90
test_chebyshev_points_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_chebyshev_points_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_compute_a_and_b_matrices.o:	../test_compute_a_and_b_matrices.f90
test_compute_a_and_b_matrices.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_compute_a_and_b_matrices.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_compute_a_and_b_matrices.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_compute_a_and_b_matrices.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_compute_a_and_b_matrices.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compute_a_and_b_matrices_mod.mod
test_compute_a_and_b_matrices_mod.mod:	../test_compute_a_and_b_matrices.f90
test_compute_a_and_b_matrices_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_compute_a_and_b_matrices_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_compute_a_and_b_matrices_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_compute_a_and_b_matrices_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_compute_a_and_b_matrices_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compute_a_and_b_matrices_mod.mod
test_compute_a_matrix.o:	../test_compute_a_matrix.f90
test_compute_a_matrix.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_compute_a_matrix.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_compute_a_matrix.o:	kernel_test_funcs_mod.mod
test_compute_a_matrix.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compute_a_matrix_mod.mod
test_compute_a_matrix_mod.mod:	../test_compute_a_matrix.f90
test_compute_a_matrix_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_compute_a_matrix_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_compute_a_matrix_mod.mod:	kernel_test_funcs_mod.mod
test_compute_a_matrix_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compute_a_matrix_mod.mod
test_constants.o:	../test_constants.f90
test_constants.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_constants.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_constants_mod.mod:	../test_constants.f90
test_constants_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_constants_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_derivs.o:	../test_derivs.f90
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compfunc_kernel_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_kernel_disc_mod.mod
test_derivs.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_derivs_mod.mod:	../test_derivs.f90
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/compfunc_kernel_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_kernel_disc_mod.mod
test_derivs_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_eigen_rankn_kernel.o:	../test_eigen_rankn_kernel.f90
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_neigen_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_eigen_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_kernel_mod.mod
test_eigen_rankn_kernel_mod.mod:	../test_eigen_rankn_kernel.f90
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_neigen_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_eigen_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/eigen_rankn_kernel_mod.mod
test_elemental.o:	../test_elemental.f90
test_elemental.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_elemental_mod.mod:	../test_elemental.f90
test_elemental_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_factorial.o:	../test_factorial.f90
test_factorial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_factorial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/factorial_mod.mod
test_factorial_mod.mod:	../test_factorial.f90
test_factorial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_factorial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/factorial_mod.mod
test_falling_factorial.o:	../test_falling_factorial.f90
test_falling_factorial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_falling_factorial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/falling_factorial_mod.mod
test_falling_factorial_mod.mod:	../test_falling_factorial.f90
test_falling_factorial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_falling_factorial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/falling_factorial_mod.mod
test_find_all_zeros.o:	../test_find_all_zeros.f90
test_find_all_zeros.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_find_all_zeros.o:	intrinsic_test_funcs_mod.mod
test_find_all_zeros.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_find_all_zeros_mod.mod:	../test_find_all_zeros.f90
test_find_all_zeros_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_find_all_zeros_mod.mod:	intrinsic_test_funcs_mod.mod
test_find_all_zeros_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_find_rel_optima.o:	../test_find_rel_optima.f90
test_find_rel_optima.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_find_rel_optima.o:	intrinsic_test_funcs_mod.mod
test_find_rel_optima.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_find_rel_optima.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
test_find_rel_optima_mod.mod:	../test_find_rel_optima.f90
test_find_rel_optima_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_find_rel_optima_mod.mod:	intrinsic_test_funcs_mod.mod
test_find_rel_optima_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_find_rel_optima_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
test_hermite_polynomial.o:	../test_hermite_polynomial.f90
test_hermite_polynomial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_hermite_polynomial.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/hermite_polynomial_mod.mod
test_hermite_polynomial_mod.mod:	../test_hermite_polynomial.f90
test_hermite_polynomial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_hermite_polynomial_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/hermite_polynomial_mod.mod
test_integral_kernel_disc.o:	../test_integral_kernel_disc.f90
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_integral_kernel_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_kernel_disc_mod.mod
test_integral_kernel_disc_mod.mod:	../test_integral_kernel_disc.f90
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_integral_kernel_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_kernel_disc_mod.mod
test_integral_rankn_disc.o:	../test_integral_rankn_disc.f90
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_integral_rankn_disc.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nsect_disc_mod.mod
test_integral_rankn_disc_mod.mod:	../test_integral_rankn_disc.f90
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_integral_rankn_disc_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/integral_nsect_disc_mod.mod
test_moore_penrose_inverse.o:	../test_moore_penrose_inverse.f90
test_moore_penrose_inverse.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_moore_penrose_inverse.o:	kernel_test_funcs_mod.mod
test_moore_penrose_inverse.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/moore_penrose_inverse_mod.mod
test_moore_penrose_inverse_mod.mod:	../test_moore_penrose_inverse.f90
test_moore_penrose_inverse_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_moore_penrose_inverse_mod.mod:	kernel_test_funcs_mod.mod
test_moore_penrose_inverse_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/moore_penrose_inverse_mod.mod
test_mrgrnk.o:	../test_mrgrnk.f90
test_mrgrnk.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_mrgrnk.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/mrgrnk_mod.mod
test_mrgrnk_mod.mod:	../test_mrgrnk.f90
test_mrgrnk_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_mrgrnk_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/mrgrnk_mod.mod
test_num_opt_rankn_kernel.o:	../test_num_opt_rankn_kernel.f90
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_num_opt_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../test_num_opt_rankn_kernel.f90
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nsect_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_num_opt_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_kernel_asymm_mod.mod
test_num_opt_rankn_params.o:	../test_num_opt_rankn_params.f90
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_num_opt_rankn_params.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_params_mod.mod
test_num_opt_rankn_params_mod.mod:	../test_num_opt_rankn_params.f90
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_num_opt_rankn_params_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/num_opt_rankn_params_mod.mod
test_quicksort.o:	../test_quicksort.f90
test_quicksort.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_quicksort.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/quicksort.mod
test_quicksort_mod.mod:	../test_quicksort.f90
test_quicksort_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_quicksort_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/quicksort.mod
test_remez_step.o:	../test_remez_step.f90
test_remez_step.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_remez_step.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_remez_step.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/remez_step_mod.mod
test_remez_step.o:	kernel_test_funcs_mod.mod
test_remez_step.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_remez_step.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/tk_simple_lapack_mod.mod
test_remez_step_mod.mod:	../test_remez_step.f90
test_remez_step_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_remez_step_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_remez_step_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/remez_step_mod.mod
test_remez_step_mod.mod:	kernel_test_funcs_mod.mod
test_remez_step_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_remez_step_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/tk_simple_lapack_mod.mod
test_set_precision.o:	../test_set_precision.f90
test_set_precision.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_set_precision_mod.mod:	../test_set_precision.f90
test_set_precision_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_singlevar_proc_ptr.o:	../test_singlevar_proc_ptr.f90
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_singlevar_proc_ptr.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
test_singlevar_proc_ptr_mod.mod:	../test_singlevar_proc_ptr.f90
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/chebyshev_points_mod.mod
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/singlevar_proc_ptr_mod.mod
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_all_zeros_mod.mod
test_singlevar_proc_ptr_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/find_rel_optima_mod.mod
test_taylor_series_rankn_kernel.o:	../test_taylor_series_rankn_kernel.f90
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nmonom_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_taylor_series_rankn_kernel.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_kernel_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../test_taylor_series_rankn_kernel.f90
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_nmonom_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_bachelier_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_blackscholes_mod.mod
test_taylor_series_rankn_kernel_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/taylor_series_rankn_kernel_mod.mod
test_unirnk.o:	../test_unirnk.f90
test_unirnk.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_unirnk.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/m_unirnk.mod
test_unirnk_mod.mod:	../test_unirnk.f90
test_unirnk_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_unirnk_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/m_unirnk.mod
test_worst_rho_and_gamma.o:	../test_worst_rho_and_gamma.f90
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_worst_rho_and_gamma.o:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod
test_worst_rho_and_gamma_mod.mod:	../test_worst_rho_and_gamma.f90
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/set_precision.mod
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/constants_mod.mod
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_expprod_mod.mod
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_gaussian_mod.mod
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/kernel_cauchy_mod.mod
test_worst_rho_and_gamma_mod.mod:	../../../../KernelyzeLibs/KernelyzeBase/KernelyzeBase/KernelyzeBaseNagDLL/worst_rho_and_gamma_mod.mod

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseTestsNag.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
intrinsic_test_funcs.o:
	@echo @nagfor intrinsic_test_funcs.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) intrinsic_test_funcs.fif -c ../intrinsic_test_funcs.f90
kernel_test_funcs.o:
	@echo @nagfor kernel_test_funcs.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) kernel_test_funcs.fif -c ../kernel_test_funcs.f90
test_set_precision.o:
	@echo @nagfor test_set_precision.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_set_precision.fif -c ../test_set_precision.f90
test_constants.o:
	@echo @nagfor test_constants.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_constants.fif -c ../test_constants.f90
test_elemental.o:
	@echo @nagfor test_elemental.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_elemental.fif -c ../test_elemental.f90
test_unirnk.o:
	@echo @nagfor test_unirnk.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_unirnk.fif -c ../test_unirnk.f90
test_mrgrnk.o:
	@echo @nagfor test_mrgrnk.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_mrgrnk.fif -c ../test_mrgrnk.f90
test_quicksort.o:
	@echo @nagfor test_quicksort.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_quicksort.fif -c ../test_quicksort.f90
test_binomial_coeffs.o:
	@echo @nagfor test_binomial_coeffs.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_binomial_coeffs.fif -c ../test_binomial_coeffs.f90
test_factorial.o:
	@echo @nagfor test_factorial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_factorial.fif -c ../test_factorial.f90
test_falling_factorial.o:
	@echo @nagfor test_falling_factorial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_falling_factorial.fif -c ../test_falling_factorial.f90
test_hermite_polynomial.o:
	@echo @nagfor test_hermite_polynomial.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_hermite_polynomial.fif -c ../test_hermite_polynomial.f90
test_singlevar_proc_ptr.o:
	@echo @nagfor test_singlevar_proc_ptr.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_singlevar_proc_ptr.fif -c ../test_singlevar_proc_ptr.f90
test_brent.o:
	@echo @nagfor test_brent.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_brent.fif -c ../test_brent.f90
test_moore_penrose_inverse.o:
	@echo @nagfor test_moore_penrose_inverse.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_moore_penrose_inverse.fif -c ../test_moore_penrose_inverse.f90
test_compute_a_matrix.o:
	@echo @nagfor test_compute_a_matrix.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_compute_a_matrix.fif -c ../test_compute_a_matrix.f90
test_compute_a_and_b_matrices.o:
	@echo @nagfor test_compute_a_and_b_matrices.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_compute_a_and_b_matrices.fif -c ../test_compute_a_and_b_matrices.f90
test_find_all_zeros.o:
	@echo @nagfor test_find_all_zeros.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_find_all_zeros.fif -c ../test_find_all_zeros.f90
test_find_rel_optima.o:
	@echo @nagfor test_find_rel_optima.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_find_rel_optima.fif -c ../test_find_rel_optima.f90
test_chebyshev_points.o:
	@echo @nagfor test_chebyshev_points.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_chebyshev_points.fif -c ../test_chebyshev_points.f90
test_remez_step.o:
	@echo @nagfor test_remez_step.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_remez_step.fif -c ../test_remez_step.f90
test_borsuk_lower_bound.o:
	@echo @nagfor test_borsuk_lower_bound.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_borsuk_lower_bound.fif -c ../test_borsuk_lower_bound.f90
test_worst_rho_and_gamma.o:
	@echo @nagfor test_worst_rho_and_gamma.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_worst_rho_and_gamma.fif -c ../test_worst_rho_and_gamma.f90
test_all_num_opt_mats_asymm.o:
	@echo @nagfor test_all_num_opt_mats_asymm.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_all_num_opt_mats_asymm.fif -c ../test_all_num_opt_mats_asymm.f90
test_num_opt_rankn_kernel.o:
	@echo @nagfor test_num_opt_rankn_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_num_opt_rankn_kernel.fif -c ../test_num_opt_rankn_kernel.f90
test_num_opt_rankn_params.o:
	@echo @nagfor test_num_opt_rankn_params.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_num_opt_rankn_params.fif -c ../test_num_opt_rankn_params.f90
test_taylor_series_rankn_kernel.o:
	@echo @nagfor test_taylor_series_rankn_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_taylor_series_rankn_kernel.fif -c ../test_taylor_series_rankn_kernel.f90
test_eigen_rankn_kernel.o:
	@echo @nagfor test_eigen_rankn_kernel.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_eigen_rankn_kernel.fif -c ../test_eigen_rankn_kernel.f90
test_integral_kernel_disc.o:
	@echo @nagfor test_integral_kernel_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_integral_kernel_disc.fif -c ../test_integral_kernel_disc.f90
test_integral_rankn_disc.o:
	@echo @nagfor test_integral_rankn_disc.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_integral_rankn_disc.fif -c ../test_integral_rankn_disc.f90
test_derivs.o:
	@echo @nagfor test_derivs.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) test_derivs.fif -c ../test_derivs.f90
fort_approx.o:
	@echo @nagfor fort_approx.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) fort_approx.fif -c ../fort_approx.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'KernelyzeBaseTestsNag.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) intrinsic_test_funcs.o kernel_test_funcs.o test_set_precision.o test_constants.o test_elemental.o test_unirnk.o test_mrgrnk.o test_quicksort.o test_binomial_coeffs.o test_factorial.o
	$(NI_RM) test_falling_factorial.o test_hermite_polynomial.o test_singlevar_proc_ptr.o test_brent.o test_moore_penrose_inverse.o test_compute_a_matrix.o test_compute_a_and_b_matrices.o test_find_all_zeros.o test_find_rel_optima.o test_chebyshev_points.o
	$(NI_RM) test_remez_step.o test_borsuk_lower_bound.o test_worst_rho_and_gamma.o test_all_num_opt_mats_asymm.o test_num_opt_rankn_kernel.o test_num_opt_rankn_params.o test_taylor_series_rankn_kernel.o test_eigen_rankn_kernel.o test_integral_kernel_disc.o test_integral_rankn_disc.o
	$(NI_RM) test_derivs.o fort_approx.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) intrinsic_test_funcs.fif kernel_test_funcs.fif test_set_precision.fif test_constants.fif test_elemental.fif test_unirnk.fif test_mrgrnk.fif test_quicksort.fif test_binomial_coeffs.fif test_factorial.fif
	$(NI_RM) test_falling_factorial.fif test_hermite_polynomial.fif test_singlevar_proc_ptr.fif test_brent.fif test_moore_penrose_inverse.fif test_compute_a_matrix.fif test_compute_a_and_b_matrices.fif test_find_all_zeros.fif test_find_rel_optima.fif test_chebyshev_points.fif
	$(NI_RM) test_remez_step.fif test_borsuk_lower_bound.fif test_worst_rho_and_gamma.fif test_all_num_opt_mats_asymm.fif test_num_opt_rankn_kernel.fif test_num_opt_rankn_params.fif test_taylor_series_rankn_kernel.fif test_eigen_rankn_kernel.fif test_integral_kernel_disc.fif test_integral_rankn_disc.fif
	$(NI_RM) test_derivs.fif fort_approx.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
